apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  namespace: kafka
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
          hostPort: 9092
        - containerPort: 9093
          hostPort: 9093
        volumeMounts:
        - name: config
          mountPath: /opt/kafka/config/cluster
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=DEBUG"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zk-cs.kafka.svc.cluster.local:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,PLAINTEXT://:9093"
        command:
        - sh
        - -c
        - "exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/cluster/server.properties"
      volumes:
      - name: config
        configMap:
          name: minikube-kafka-config-map
          items:
          - key: server.properties
            path: server.properties

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: minikube-kafka-config-map
  namespace: kafka
  labels:
    name: minikube-kafka-config-map
data:
  server.properties: |-
    broker.id=0
    port=9092
    default.replication.factor=1
    zookeeper.connect=zk-cs.kafka.svc.cluster.local:2181
